name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test (ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout V
        uses: actions/checkout@v7
        with:
          repository: vlang/v

      - name: Checkout i18n
        uses: actions/checkout@v7
        with:
          path: i18n

      - name: Build V
        run: |
          make
          ./v symlink -githubci

      - name: Test
        working-directory: i18n
        run: v test .
