name: CI

on:
  push:
    branches:
      - stable
      - dev
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Check and test.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup V
        uses: vlang/setup-v@v1.7

      - name: Check
        run: v -old-compiler -check .

      - name: Test
        run: v -old-compiler test .
